bootstrap/urls.py
from django.urls import path, include
from django.contrib import admin
from bootstrap import views


app_name='bootstrap'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bsHome/', views.bsHome, name='bsHome'),
    path('bsList/', views.bsList, name='bsList'),
    path('bsAdd/', views.bsAdd, name='bsAdd'),
    path('bsEdit/<int:bs_id>/', views.bsEdit, name='bsEdit'),
    path('bsReform/<int:bs_id>/', views.bsReform, name='bsReform'),
]

course/urls.py
from django.urls import path, include
from django.contrib import admin
from course import views


app_name='course'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courseHome/', views.courseHome, name='courseHome'),

    path('bootstrap/', views.bootstrap, name='bootstrap'),
    path('courseAdd/', views.courseAdd, name='courseAdd'),
    path('courseEdit/<int:course_id>/', views.courseEdit, name='courseEdit'),
    path('courseReform/<int:course_id>/', views.courseReform, name='courseReform'),
]

main/urls.py
from django.urls import path, include
from django.contrib import admin
from main import views

app_name='main'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('index/', views.index, name='index'),

    path('login/', views.login, name='login'),
    path('join/', views.join, name='join'),
    path('logout/', views.logout, name='logout'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

# for ckeditor
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('main/', include('main.urls', namespace='main')),

    path('ckeditor/', include('ckeditor_uploader.urls')),         # for ckeditor

    path('course/', include('course.urls', namespace='course')),
    path('python/', include('python.urls', namespace='python')),
    path('mLearn/', include('mLearn.urls', namespace='mLearn')),
    path('bootstrap/', include('bootstrap.urls', namespace='bootstrap')),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python/urls.py
from django.urls import path, include
from django.contrib import admin
from python import views


app_name='python'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pyHome/', views.pyHome, name='pyHome'),
    path('pyAdd/', views.pyAdd, name='pyAdd'),
    path('pyEdit/<int:py_id>/', views.pyEdit, name='pyEdit'),
    path('pyReform/<int:py_id>/', views.pyReform, name='pyReform'),
    path('pyTest/', views.pyTest, name='pyTest'),
]

bootstrap/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
#from ckeditor_uploader.widgets import CKEditorUploadingWidget  # image 처리가능
from django.urls import reverse
# Create your models here.

class Bs(models.Model):

    subject=models.CharField(max_length=30, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(auto_now_add=True)  # 레코드 생성시 현재 시간으로 자동 저장
    updated_at = models.DateTimeField(auto_now=True)  # 레코드 업데이트시 현재 시간으로 자동 저장

    class Meta:
        ordering = ['-id']   # - : reverse

bootstrap/forms.py
from django import forms

# from ckeditor.widgets import CKEditorWidget                   # 일반적 처리가능
from ckeditor_uploader.widgets import CKEditorUploadingWidget   # image 포함 처리가능

from .models import Bs

class BsForm(forms.ModelForm):

    # content = forms.CharField(widget=CKEditorWidget())
    content = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = Bs
        fields = ('subject', 'content', )
        # fields = '__all__'

bootstrap/views.py
from django.shortcuts import render, redirect, get_object_or_404

# message불러올때
from django.contrib import messages

# decorator 불러들일때
from django.contrib.auth.decorators import login_required

# Model, Form 불러올때
from .forms import BsForm
from .models import Bs

# Create your views here.
def bsHome(request):
    bsList = Bs.objects.all()
    item = Bs.objects.get(id=1)

    data = {
        'bsList': bsList,
        'item': item,
    }
    return render(request, 'bootstrap/bsHome.html', data)

# @login_required
def bsList(request):
    bsList = Bs.objects.all()
    item = Bs.objects.get(id=1)

    data = {
        'bsList': bsList,
        'item': item,
    }
    return render(request, 'bootstrap/bsList.html')

@login_required
def bsAdd(request):

    if request.method == 'POST':
        form = BsForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            messages.success(request, "New BS was successfully added!")
            return redirect('bootstrap:bsHome')

    else:
        form = BsForm()
        data = {
            'form' : form,
            # 'csrfmiddlewaretoken': '{{ csrf_token }}',
        }
    return render(request, 'bootstrap/bsForm.html', data)



def bsEdit(request, bs_id):
    bsList = Bs.objects.all()
    item = get_object_or_404(Bs, pk=bs_id)

    data = {
        'bsList' : bsList,
        'item' : item,
    }

    return render(request, 'bootstrap/bsEdit.html', data)

def bsReform(request, bs_id):

    item = get_object_or_404(Bs, pk=bs_id)

    if request.method == 'POST':
        form = BsForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            messages.success(request, 'New boostrap was successfully edited!')
            return redirect('bootstrap:bsHome')

    else:
        form = BsForm(instance=item)
        data ={
            'form' : form,
        }
    return render(request, 'bootstrap/bsForm.html', data)

bootstrap/templates/bootstrap/bsEdit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block sidebar %}
<div class="col-sm-3">
    {% include 'bootstrap/sidebar.html' with objects=bsList %}
</div>
{% endblock %}

{% block content %}
<div class="col-sm-9">
    {{form.media }}
    {{item.content|safe }}
</div>
{% endblock %}

bootstrap/templates/bootstrap/bsForm.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<!--# option2: 각자 필드에 적용(특정 항목 수정가능) -->
<div class="content_bsForm">

  <!--#option2 각자 필드를 부트스트랩 적용(crispy)-->
  <form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.media }}

    <div class="col">
      {{ form.subject|as_crispy_field }}
    </div>

    <div class="col">
      {{form.media }}
      {{form.content|safe }}
    </div>

    <div class="d-flex justify-content-around">
	    <input class="col-3 btn btn-secondary form-control" type="button" value="이전화면"  onclick="history.back(); return false;">
		<input class="col-3 btn btn-primary form-control" type="submit" value="게시글 등록">
    </div>

  </form>

</div>
{% endblock %}

bootstrap/templates/bootstrap/bsHome.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


<div>
    {% block sidebar %}
    <div class="col-sm-3">
        {% include 'bootstrap/sidebar.html' with objects=bsList %}
    </div>
    {% endblock %}

    {% block content %}
    <div class="col-sm-9">
          {{form.media }}
          {{item.content|safe }}
    </div>
    {% endblock %}
</div>

bootstrap/templates/bootstrap/bsList.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


<div>
    {% block sidebar %}
    <div class="col-sm-3">
        {% include 'bootstrap/sidebar.html' with objects=bsList %}
    </div>
    {% endblock %}

    {% block content %}
    <div class="col-sm-9">
          {{form.media }}
          {{item.content|safe }}
    </div>
    {% endblock %}
</div>

bootstrap/templates/bootstrap/sidebar.html
<div id="sidebar">
    <h3>Bootstrap4 예문</h3>
    <h5>진행형자습서:</h5>


    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a class="nav-link text-primary"  href="{% url 'bootstrap:bsHome' %}"><i class="icon-home icon-white"></i> Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link"  href="{% url 'course:courseHome' %}"><i class="icon-book"></i> Django</a>
        </li>
        <li class="nav-item">
            <a class="nav-link"  href="{% url 'python:pyHome' %}"><i class="icon-book"></i> Python</a>
        </li>

        {% for item in bsList %}
        <li class="nav-item">
            <div class="row">
                <a class="nav-link"  href="{% url 'bootstrap:bsEdit' item.id %}"><i class="icon-book"></i>{{item.subject}}</a>
                <a class="nav-link"  href="{% url 'bootstrap:bsReform' item.id %}"><i class="icon-book"></i>#</a>
            </div>
        </li>
        {% endfor %}

        <li class="nav-item">
            <a class="nav-link"  href="{% url 'bootstrap:bsAdd' %}"><i class="icon-book"></i> Bootstrap-Add</a>
        </li>

        <li class="nav-item">
            <a class="nav-link"  href="{% url 'bootstrap:bsList' %}"><i class="icon-book"></i> bootstrap4(예문)</a>
        </li>
    </ul>

    <form class="navbar-search pull-left">
        <input type="text" class="search-query" placeholder="Search">
    </form>

    <hr class="d-sm-none">

</div>