course/urls.py
from django.urls import path, include
from django.contrib import admin
from course import views


app_name='course'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courseHome/', views.courseHome, name='courseHome'),

    path('bootstrap/', views.bootstrap, name='bootstrap'),
    path('courseAdd/', views.courseAdd, name='courseAdd'),
    path('courseEdit/<int:course_id>/', views.courseEdit, name='courseEdit'),
    path('courseReform/<int:course_id>/', views.courseReform, name='courseReform'),
]

main/urls.py
from django.urls import path, include
from django.contrib import admin
from main import views

app_name='main'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('index/', views.index, name='index'),

    path('login/', views.login, name='login'),
    path('join/', views.join, name='join'),
    path('logout/', views.logout, name='logout'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

# for ckeditor
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('main/', include('main.urls', namespace='main')),

    path('ckeditor/', include('ckeditor_uploader.urls')),         # for ckeditor

    path('course/', include('course.urls', namespace='course')),
    path('python/', include('python.urls', namespace='python')),
    path('mLearn/', include('mLearn.urls', namespace='mLearn')),
    path('bootstrap/', include('bootstrap.urls', namespace='bootstrap')),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python/urls.py
from django.urls import path, include
from django.contrib import admin
from python import views


app_name='python'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pyHome/', views.pyHome, name='pyHome'),
    path('pyAdd/', views.pyAdd, name='pyAdd'),
    path('pyEdit/<int:py_id>/', views.pyEdit, name='pyEdit'),
    path('pyReform/<int:py_id>/', views.pyReform, name='pyReform'),
    path('pyTest/', views.pyTest, name='pyTest'),
]

python/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Python(models.Model):

    subject=models.CharField(max_length=30, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(auto_now_add=True)  # 레코드 생성시 현재 시간으로 자동 저장
    updated_at = models.DateTimeField(auto_now=True)  # 레코드 업데이트시 현재 시간으로 자동 저장

    class Meta:
        ordering = ['-id']   # - : reverse

python/forms.py
from django import forms

# from ckeditor.widgets import CKEditorWidget                   # 일반적 처리가능
from ckeditor_uploader.widgets import CKEditorUploadingWidget  # image 포함 처리가능

from .models import Python

class PythonForm(forms.ModelForm):

    # content = forms.CharField(widget=CKEditorWidget())
    content = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = Python
        fields = ('subject', 'content', )
        # fields = '__all__'

python/views.py
from django.shortcuts import render, redirect, get_object_or_404

# message불러올때
from django.contrib import messages

# decorator 불러들일때
from django.contrib.auth.decorators import login_required

# Model, Form 불러올때
from .forms import PythonForm
from .models import Python
from course.models import Course

# Create your views here.
def pyHome(request):
    pyList = Python.objects.all()
    # item = Python.objects.get(id=1)
    item = Course.objects.get(id=1)

    data = {
        'pyList': pyList,
        'item': item,
    }

    return render(request, 'python/pyHome.html', data)

# @login_required
def pyAdd(request):

    if request.method == 'POST':
        form = PythonForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            messages.success(request, "New Python was successfully added!")
            return redirect('python:pyHome')

    else:
        form = PythonForm()
        data = {
            'form' : form,
            # 'csrfmiddlewaretoken': '{{ csrf_token }}',
        }
    return render(request, 'python/pyForm.html', data)

def pyEdit(request, py_id):
    pyList = Python.objects.all()
    item = get_object_or_404(Python, pk=py_id)

    data = {
        'pyList' : pyList,
        'item' : item,
    }

    return render(request, 'python/pyEdit.html', data)

def pyReform(request, py_id):

    item = get_object_or_404(Python, pk=py_id)

    if request.method == 'POST':
        form = PythonForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            messages.success(request, 'New python was successfully edited!')
            return redirect('python:pyHome')

    else:
        form = PythonForm(instance=item)
        data ={
            'form' : form,
        }
    return render(request, 'python/pyForm.html', data)


##For TEST ##############################################################
def pyTest(request):
    ###############################





    ################################
    return render(request, 'python/pyHome.html')



###End TEST#########################################################################

python/templates/python/pyEdit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block sidebar %}
<div class="col-sm-3">
    {% include 'python/sidebar.html' with objects=pyList %}
</div>
{% endblock %}

{% block content %}
<div class="col-sm-9">
    {{form.media }}
    {{item.content|safe }}

    <p class="totop"><a href="#top">Back to top</a></p>
</div>
{% endblock %}

python/templates/python/pyForm.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<!--# option2: 각자 필드에 적용(특정 항목 수정가능) -->
<div class="content_mLearnForm">

  <!--#option2 각자 필드를 부트스트랩 적용(crispy)-->
  <form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.media }}

    <div class="col">
      {{ form.subject|as_crispy_field }}
    </div>

    <div class="col">
      {{form.media }}
      {{form.content|safe }}
    </div>

    <div class="d-flex justify-content-around">
	    <input class="col-3 btn btn-secondary form-control" type="button" value="이전화면"  onclick="history.back(); return false;">
		<input class="col-3 btn btn-primary form-control" type="submit" value="게시글 등록">
    </div>

  </form>

</div>
{% endblock %}

python/templates/python/pyHome.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


<div>

    {% block sidebar %}
    <div class="col-sm-3">
        {% include 'python/sidebar.html' with objects=pyList %}
    </div>
    {% endblock %}

    {% block content %}
    <div class="col-sm-9">
          {{form.media }}
          {{item.content|safe }}
    </div>
    {% endblock %}

</div>

python/templates/python/sidebar.html
<div id="sidebar">
    <h3>Python</h3>
    <h5>진행형자습서:</h5>


    <ul class="nav nav-pills flex-column ">
        <li class="nav-item">
            <a class="nav-link text-primary"  href="{% url 'python:pyHome' %}"><i class="icon-home icon-white"></i> Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link"  href="{% url 'course:courseHome' %}"><i class="icon-book"></i> Django</a>
        </li>

        <li class="nav-item">
            <a class="nav-link"  href="{% url 'python:pyTest' %}"><i class="icon-book"></i> EX-python</a>
        </li>
        <li class="nav-item">
            <a class="nav-link"  href="{% url 'python:pyAdd' %}"><i class="icon-book"></i> python-Add</a>
        </li>

        {% for item in pyList %}
        <li class="nav-item">
            <div class="row">
                <a class="nav-link"  href="{% url 'python:pyEdit' item.id  %}"><i class="icon-book"></i>{{item.subject}}</a>
                <a class="nav-link"  href="{% url 'python:pyReform' item.id %}"><i class="icon-book"></i>#</a>

            </div>
        </li>
        {% endfor %}



        <li class="nav-item">
            <a class="nav-link disabled" href="#"># 수정</a>
        </li>
    </ul>

    <form class="navbar-search pull-left">
        <input type="text" class="search-query" placeholder="Search">
    </form>

    <hr class="d-sm-none">

</div>