bootstrap/urls.py
from django.urls import path, include
from django.contrib import admin
from bootstrap import views


app_name='bootstrap'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bsHome/', views.bsHome, name='bsHome'),
    path('bsList/', views.bsList, name='bsList'),
    path('bsAdd/', views.bsAdd, name='bsAdd'),
    path('bsEdit/<int:bs_id>/', views.bsEdit, name='bsEdit'),
    path('bsReform/<int:bs_id>/', views.bsReform, name='bsReform'),
]

course/urls.py
from django.urls import path, include
from django.contrib import admin
from course import views


app_name='course'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courseHome/', views.courseHome, name='courseHome'),

    path('bootstrap/', views.bootstrap, name='bootstrap'),
    path('courseAdd/', views.courseAdd, name='courseAdd'),
    path('courseEdit/<int:course_id>/', views.courseEdit, name='courseEdit'),
    path('courseReform/<int:course_id>/', views.courseReform, name='courseReform'),
]

mLearn/urls.py
from django.urls import path, include
from django.contrib import admin
from mLearn import views


app_name='mLearn'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mLearnHome/', views.mLearnHome, name='mLearnHome'),
    path('mLearnAdd/', views.mLearnAdd, name='mLearnAdd'),
    path('mLearnEdit/<int:mLearn_id>/', views.mLearnEdit, name='mLearnEdit'),
    path('mLearnReform/<int:mLearn_id>/', views.mLearnReform, name='mLearnReform'),
    path('exHome/', views.exHome, name='exHome'),
    path('download/', views.download, name='download'),
    path('beautifulSoup/', views.beautifulSoup, name='beautifulSoup'),
    path('pandas/', views.pandas, name='pandas'),
    path('select/', views.select, name='select'),
    path('path/', views.path, name='path'),
    path('login/', views.login, name='login'),
    path('weather/', views.weather, name='weather'),
    path('selenium/', views.selenium, name='selenium'),
    path('mysql/', views.mysql, name='mysql'),
    path('datatype/', views.datatype, name='datatype'),
    path('jsontype/', views.jsontype, name='jsontype'),
    path('xmltype/', views.xmltype, name='xmltype'),
    path('csvtype/', views.csvtype, name='csvtype'),
    path('excel/', views.excel, name='excel'),
    path('plot/', views.plot, name='plot'),
    path('image/', views.image, name='image'),
    path('scikit/', views.scikit, name='scikit'),
    path('mLearnTest/', views.mLearnTest, name='mLearnTest'),
    path('conversion/', views.conversion, name='conversion'),
    path('lang/', views.lang, name='lang'),
    path('langTest/', views.langTest, name='langTest'),
    path('fat/', views.fat, name='fat'),
    path('mushroom/', views.mushroom, name='mushroom'),
    path('tensor/', views.tensor, name='tensor'),
    path('mnist/', views.mnist, name='mnist'),


]

main/urls.py
from django.urls import path, include
from django.contrib import admin
from main import views

app_name='main'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('index/', views.index, name='index'),

    path('login/', views.login, name='login'),
    path('join/', views.join, name='join'),
    path('logout/', views.logout, name='logout'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

# for ckeditor
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('main/', include('main.urls', namespace='main')),

    path('ckeditor/', include('ckeditor_uploader.urls')),         # for ckeditor

    path('course/', include('course.urls', namespace='course')),
    path('python/', include('python.urls', namespace='python')),
    path('mLearn/', include('mLearn.urls', namespace='mLearn')),
    path('bootstrap/', include('bootstrap.urls', namespace='bootstrap')),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python/urls.py
from django.urls import path, include
from django.contrib import admin
from python import views


app_name='python'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pyHome/', views.pyHome, name='pyHome'),
    path('pyAdd/', views.pyAdd, name='pyAdd'),
    path('pyEdit/<int:py_id>/', views.pyEdit, name='pyEdit'),
    path('pyReform/<int:py_id>/', views.pyReform, name='pyReform'),
    path('pyTest/', views.pyTest, name='pyTest'),
]

main/models.py
from django.db import models


# Create your models here.
# class JoinMember(models.Model):
#
#
#     username = models.CharField(max_length=100)
#     password = models.CharField(max_length=130)
#     email = models.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
#     address = models.CharField(max_length=130)
#
#     class Meta:
#         ordering = ['-id']   # - : reverse

main/forms.py
from django import forms
from django.contrib.auth.models import User        # 'auth.User' table
from django.contrib.auth.forms import UserCreationForm
# from .models import JoinMember


# ModelForm활용한 로그인 접근
class LoginForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'password',]

# Form을 이용하여
# class JoinForm(forms.Form):
    # username = forms.CharField()
    # last_name = forms.CharField()
    # first_name = forms.CharField()
    # password = forms.CharField()
    # email = forms.CharField()
    # address = forms.CharField()

    # class Meta:
    #     model = JoinMember
    #     fields = ('username', 'address', 'first_name', 'last_name', 'email', 'password',)


# ModelForm을 이용하여
class JoinForm(forms.ModelForm):

    class Meta:
        # model = JoinMember
        model = User
        fields = ['username', 'email', 'password', ]
        # fields = '__all__'

# class JoinUserForm(forms.ModelForm):
class JoinUserForm(UserCreationForm):
    address = forms.CharField(max_length=100, required=False)

    class Meta:
        model = User
        fields = ('username', 'address', 'email', 'password1', 'password2',)

#UserCreationForm을 통한 간편 회원 가입
# class JoinForm(UserCreationForm):
#
#     class Meta:
#         model = User
#         fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'email',)

main/views.py
from django.shortcuts import render, redirect


#http 출력위함
from django.http import HttpResponse, HttpResponseRedirect

# django app(auth) Model-authenticate, login 활용
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# message불러올때
from django.contrib import messages

#form(회원등록폼,) 불러올때
from .forms import LoginForm, JoinForm, JoinUserForm

# decorator 불러들일때
from django.contrib.auth.decorators import login_required
# from main.decorators import user_is_entry_author


def index(request):

    if request.method == "POST":
        projectname = request.POST['projectname']

        print(projectname)

        # return HttpResponse("Welcome Home")
        # return render(request, 'main/index.html')
        return render(request, 'main/index.html', {'projectname':projectname})

    else:
        return render(request, 'main/index.html')


## ajax를 이용한 로그인
def login(request):

    if request.method == "POST":

        form = LoginForm(request.POST)

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user is not None :

            auth_login(request, user)

            # session 설정하여 나중에 활용
            m = User.objects.get(username=request.POST['username'])

            request.session['member_id'] = m.id
            request.session['member_username'] = m.username


            return HttpResponse("Welcome My Python Tutorial")   # ajax 리턴의 경우 String으로 리턴
            # return redirect('index')

        else:
            return HttpResponse('로그인 실퍠.  다시 시도하세요.')

    else:
        form = LoginForm()

        return render(request, 'main/login.html', {'form':form})


def logout(request):

    del request.session['member_id']

    auth_logout(request)

    # return redirect('index')
    return render(request, 'main/index.html')


# ajax를 이용한
def join(request):
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = JoinUserForm(request.POST)
        print(form)

        if form.is_valid():

            form.save()
            new_user = User.objects.create_user(**form.cleaned_data)  # User에 저장(create_user())

            # 옵션 저장 다른 표현
            # new_user=form.save(commit=False)  # 저장 객체 생성, 장장 실행하지 않음
            # new_user.email=request.User.get_email()  # 추가적 User의 email을 이곳 이메일로 지정
            # new_user.generate() # 새로운 User db 저장

            login(request, new_user)  # login 함수 실행

            return HttpResponse("Welcome My World")  #return redirect('index') #url의 name을 경로대신 입력한다.(여기는 ajax 때문에 문자열 리턴)
    else:
        form = JoinUserForm()  #forms.py의 JoinUserForm 클래스의 인스턴스
        return render(request, 'main/join.html', {'form': form})   # 템플릿 파일 경로 지정, 데이터 전달

# ajax를 이용한 회원가입
# def join(request):
#
#     if request.method == "POST":
#
#         # create a form instance and populate it with data from the request:
#         form = JoinForm(request.POST)
#         # form = UserCreationForm(request.POST)
#
#         if form.is_valid():
#
#
#
#             messages.success(request, "New BS was successfully added!")
#             # user.refresh_from_db()  # load the profile instance created by the signal
#
#             username = form.cleaned_data.get('username')
#             raw_password = form.cleaned_data.get('password')
#
#             print(raw_password)
#
#             user = authenticate(username=username, password=raw_password)
#
#             print(user)
#
#             auth_login(request, user)                         # login 함수 자동 연결 실행
#
#
#
#             # session 설정하여 나중에 활용
#             m = User.objects.get(username=request.POST['username'])
#
#             request.session['member_id'] = m.id
#             request.session['member_username'] = m.username
#
#             # return redirect('main:index')
#
#
#             return HttpResponse("Welcome My Python Tutorial")
#             # return redirect('index')       #url의 name을 경로대신 입력한다.(여기는 ajax 때문에 문자열 리턴)
#             # return render(request, 'main/index.html')
#
#     else:
#
#         form = JoinForm()                                               #forms.py의 JoinForm 클래스의 인스턴스
#         # form = UserCreationForm()
#
#         return render(request, 'main/join.html', {'form': form})   # 템플릿 파일 경로 지정, 데이터 전달

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">

#body_index{
	background-image:url("{% static '/image/main/city_night.jpg' %}");
}

img {
  display: block;
  max-width:230px;
  max-height:95px;
  width: auto;
  height: auto;
}

/* @media screen and (max-width:768px){
  .card-body{max-height:2em; padding:0;align:center;}
  .card-title{margin:0;align:center;font-size: 0.3em; }
} */

</style>

<script type="text/javascript">

function addPro(){
	var obj1 = document.addForm;

	if(obj1.projectname.value==""){alert("아이디를 입력해주세요"+screen.width + '50'); return;}

<!--	var projectname = obj1.projectname.value;-->

<!--	alert(projectname);-->

<!--	window.location.href = '/main/index/'+ projectname + '/';-->

	var dataList1 = {
		"projectname" : obj1.projectname.value,
		'csrfmiddlewaretoken': '{{ csrf_token }}'
	};

	alert(dataList1);

	var url1 = "{% url 'main:index' %}";

	$.ajax({
		type : "POST",
		url : url1,
		async : false,
		data : dataList1,
		success : function(data){
			console.log("data: ", data)


		}
	});
}

<!--첫화면 에니메이션 처리-->
$(function(){

    $("dd").slice(0, 6).show(); 					// select the first 6

    $("#loadMore").click(function(e){ 				// click event for load more
        e.preventDefault();
        $("dd:hidden").slice(0, 3).show(); 			// select next 3 hidden divs and show them
        if($("div:hidden").length == 0){ 			// check if any hidden divs still exist
        	$("#loadMore").fadeOut('slow');
            	//alert("No more divs"); 			// alert if there are none left
        	}
        $('html,body').animate({
            scrollTop: $(this).offset().top
        }, 1500);
    });
});

</script>
<script src="{% static 'js/more_load.js' %}"></script>

<div id="body_index" class="p-5">

    <!-- main content -->
    <div class="row col-md-10 offset-md-1 d-flex justify-content-around">

		<dd class="col-4 mb-4" style="display:none;">
			<div class="card" id="more"  >
	    		<a href="{% url 'python:pyHome' %}"><img class="card-img-top img-fluid rounded" src="{% static '/image/green/green_6.jpg' %}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'python:pyHome' %}"><h6 class="card-title" style="font-size:3vw">Python</h6></a>
	    		</div>
	  		</div>
		</dd>
		<dd class="col-4 mb-4" style="display:none;">
			<div class="card" id="more"  >
	    		<a href="{% url 'course:courseHome' %}"><img class="card-img-top img-fluid rounded" src="{% static '/image/green/green_6.jpg' %}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'course:courseHome' %}"><h6 class="card-title" style="font-size:3vw">Django</h6></a>
	    		</div>
	  		</div>
		</dd>
		<dd class="col-4 mb-4" style="display:none;">
			<div class="card" id="more"  >
	    		<a href="{% url 'mLearn:mLearnHome' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_6.jpg' %}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'mLearn:mLearnHome' %}"><h6 class="card-title" style="font-size:3vw">mLearn</h6></a>
	    		</div>
	  		</div>
		</dd>
		<dd class="col-4 mb-4" style="display:none;">
			<div class="card" id="more"  >
	    		<a href="{% url 'bootstrap:bsHome' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_6.jpg' %}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'bootstrap:bsHome' %}"><h7 class="card-title" style="font-size:3vw">Bootstrap</h7></a>
	    		</div>
	  		</div>
		</dd>
		{{projectname}}
		{% if projectname %}
		<dd class="col-4 mb-4" style="display:none;">
			<div class="card" id="more"  >
	    		<a href="{% url 'bootstrap:bsHome' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_6.jpg' %}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'bootstrap:bsHome' %}"><h7 class="card-title" style="font-size:3vw">{{projectname}}</h7></a>
	    		</div>
	  		</div>
		</dd>
		{% endif %}

	</div>

	<div class="text-center">
<!--		<a type="button" class="btn btn-success" href="#addModal" data-toggle="modal">add Project</a>-->
		<input type="button" id="loadMore" class="btn btn-success" value="더보기" />
		<input type="button" class="btn btn-success" value="돌아가기" onclick="history.back(); return false ;" />
	</div>

  	<p class="totop"><a href="#top">Back to top</a></p>

	<!--==========================================================================-->
	<!-- The Add Modal 이용시 -->
	<div class="modal" id="addModal">
	  <div class="modal-dialog">

	    <div class="modal-content">

	    <!-- // 폼형태로 입력하여 ajax 형태로 전달 -->
		<form name="addForm" method="post" onSubmit="return addCheck()">

	      <!-- Modal Header -->
	      <div class="modal-header">
	        <h4 class="modal-title">프로젝트명</h4>
	        <button type="button" class="close" data-dismiss="modal">&times;</button>
	      </div>

	      <!-- Modal body -->
	      <div class="modal-body">
	        <span class="fa fa-envelope"></span> 프로젝트명 <br />
			<input type="text" class="form-control" name="projectname" /><br /> <br />
	      </div>

	      <!-- Modal footer -->
	      <div class="modal-footer">
	      	<button type="button" class="btn" data-dismiss="modal">Close</button>
	      	<button type="button" class="btn btn-success" onclick="addPro()">추가</button>
	      </div>

		</form>
	    </div>
	  </div>
	</div>
    <!--end add modal-->

</div>     <!-- end of body_container -->
{% endblock %}

main/templates/main/join.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Join
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'main:join' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">회원가입</button>
    </form>

{% endblock %}

main/templates/main/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}
  <h2>Login</h2>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Login</button>
  </form>

{% endblock %}

main/templates/main/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Sign up</button>
  </form>
{% endblock %}