mLearn/urls.py
from django.urls import path, include
from django.contrib import admin
from mLearn import views


app_name='mLearn'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mLearnHome/', views.mLearnHome, name='mLearnHome'),
    path('mLearnAdd/', views.mLearnAdd, name='mLearnAdd'),
    path('mLearnEdit/<int:mLearn_id>/', views.mLearnEdit, name='mLearnEdit'),
    path('mLearnReform/<int:mLearn_id>/', views.mLearnReform, name='mLearnReform'),
    path('exHome/', views.exHome, name='exHome'),
    path('download/', views.download, name='download'),
    path('beautifulSoup/', views.beautifulSoup, name='beautifulSoup'),
    path('pandas/', views.pandas, name='pandas'),
    path('select/', views.select, name='select'),
    path('path/', views.path, name='path'),
    path('login/', views.login, name='login'),
    path('weather/', views.weather, name='weather'),
    path('selenium/', views.selenium, name='selenium'),
    path('mysql/', views.mysql, name='mysql'),
    path('datatype/', views.datatype, name='datatype'),
    path('jsontype/', views.jsontype, name='jsontype'),
    path('xmltype/', views.xmltype, name='xmltype'),
    path('csvtype/', views.csvtype, name='csvtype'),
    path('excel/', views.excel, name='excel'),
    path('plot/', views.plot, name='plot'),
    path('image/', views.image, name='image'),
    path('scikit/', views.scikit, name='scikit'),
    path('mLearnTest/', views.mLearnTest, name='mLearnTest'),
    path('conversion/', views.conversion, name='conversion'),
    path('lang/', views.lang, name='lang'),
    path('langTest/', views.langTest, name='langTest'),
    path('fat/', views.fat, name='fat'),
    path('mushroom/', views.mushroom, name='mushroom'),
    path('tensor/', views.tensor, name='tensor'),
    path('mnist/', views.mnist, name='mnist'),


]

main/urls.py
from django.urls import path, include
from django.contrib import admin
from main import views

app_name='main'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('index/', views.index, name='index'),

    path('login/', views.login, name='login'),
    path('join/', views.join, name='join'),
    path('logout/', views.logout, name='logout'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

# for ckeditor
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('main/', include('main.urls', namespace='main')),

    path('ckeditor/', include('ckeditor_uploader.urls')),         # for ckeditor

    path('course/', include('course.urls', namespace='course')),
    path('python/', include('python.urls', namespace='python')),
    path('mLearn/', include('mLearn.urls', namespace='mLearn')),
    path('bootstrap/', include('bootstrap.urls', namespace='bootstrap')),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mLearn/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
#from ckeditor_uploader.widgets import CKEditorUploadingWidget  # image 처리가능
from django.urls import reverse

# Create your models here.
class MLearn(models.Model):

    subject=models.CharField(max_length=30, verbose_name='제목')
    # subject = forms.CharField(
    #     max_length=200,
    #     widget=forms.TextInput(
    #         attrs={
    #             'style': 'border-color:blue',
    #             'placeholder': 'write tile here'
    #         }
    #     ))
    # category = models.CharField('카테고리', max_length=10, choices=TYPE_CHOICES)

    # created_by = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='작성자')
    # writer=models.CharField(max_length=100, verbose_name='작성자', help_text='비회원경우, 별명 입력')

    content = models.TextField(verbose_name='내용')
    # content = models.TextField(verbose_name='내용', widget=CKEditorUploadingWidget())
    # content = RichTextUploadingField(verbose_name='내용')

    # upload = models.FileField(upload_to='uploaded/', verbose_name='업로드파일' )

    created_at = models.DateTimeField(auto_now_add=True)  # 레코드 생성시 현재 시간으로 자동 저장
    updated_at = models.DateTimeField(auto_now=True)  # 레코드 업데이트시 현재 시간으로 자동 저장

    class Meta:
        ordering = ['-id']   # - : reverse

mLearn/forms.py
from django import forms

# from ckeditor.widgets import CKEditorWidget                   # 일반적 처리가능
from ckeditor_uploader.widgets import CKEditorUploadingWidget  # image 포함 처리가능

from .models import MLearn

class MLearnForm(forms.ModelForm):

    # content = forms.CharField(widget=CKEditorWidget())
    content = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = MLearn
        fields = ('subject', 'content', )
        # fields = '__all__'

mLearn/views.py
from django.shortcuts import render, redirect, get_object_or_404

# message불러올때
from django.contrib import messages

# 외부자료 입력할때
import sys

from .forms import MLearnForm
from .models import MLearn

# decorator 불러들일때
from django.contrib.auth.decorators import login_required

## 데이터 추출
# urllib.request 사용 (데이터 다운로드)
import urllib.request

# requests 패키지 사용(고급)
import requests
# urlencode() 사용하기 위함 : 매개변수 처리
import urllib.parse

# BeautifulSoup4 운용
from bs4 import BeautifulSoup

# 상대경로를 절대경로로 전환위해
from urllib.parse import urljoin

# json 정보 처리위해
import json

# 정규표현식 사용할때
import re

# selenium을 통해 웹브라우저 접근시
from selenium import webdriver

# mysql 연결위해
import pymysql

# path내 파일 존재유무 확인시
import os.path, glob                        ## 차이 :  from django.urls import path

# csv 파일 처리위해
import csv

# excel 파일 처리
import openpyxl

# pandas 분석 처리
import pandas as pd

# numpy(다차원 배열 처리)
import numpy as np

# metplotlib(PLOT처리)
from matplotlib import pyplot as plt

# Pillow를 이용한 이미지 처리
from PIL import Image
# OpenCV를 통한 이미지/영상 처리
import cv2

# scikit Learn 활용위해
from sklearn import svm, metrics
# joblib 모듈 사용위해
# from sklearn.externals import joblib
import joblib

# random 숫자 추출
import random

from sklearn.model_selection import train_test_split

# gzio 압축 해제
import gzip

# cgi 처리 위해
import cgi

# RandonForestClassifier 처리위해
from sklearn.ensemble import RandomForestClassifier
# TensorFlow 사용을 위해
# import tensorflow as tf



# =============================================================
# Create your views here.
def mLearnHome(request):
    mLearnList = MLearn.objects.all()
    item = MLearn.objects.get(id=4)

    data = {
        'mLearnList': mLearnList,
        'item': item,
    }

    return render(request, 'mLearn/mLearnHome.html', data)

# @login_required
def mLearnAdd(request):

    if request.method == 'POST':
        form = MLearnForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            messages.success(request, "New MLearn was successfully added!")
            return redirect('mLearn:mLearnHome')

    else:
        form = MLearnForm()
        data = {
            'form' : form,
            # 'csrfmiddlewaretoken': '{{ csrf_token }}',
        }
    return render(request, 'mLearn/mLearnForm.html', data)

def mLearnEdit(request, mLearn_id):
    mLearnList = MLearn.objects.all()
    item = get_object_or_404(MLearn, pk=mLearn_id)

    data = {
        'mLearnList' : mLearnList,
        'item' : item,
    }

    return render(request, 'mLearn/mLearnEdit.html', data)

def mLearnReform(request, mLearn_id):

    item = get_object_or_404(MLearn, pk=mLearn_id)

    if request.method == 'POST':
        form = MLearnForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            messages.success(request, 'New mLearn was successfully edited!')
            return redirect('mLearn:mLearnHome')

    else:
        form = MLearnForm(instance=item)
        data ={
            'form' : form,
        }
    return render(request, 'mLearn/mLearnForm.html', data)


# Exercise ========================================================================
def exHome(request):
    return render(request, 'mLearn/exHome.html')

def download(request):

    ##1. urlretrieve() 저장
    savename = "C:/Users/ilee/PycharmProjects/mLearn/test.png"
    url1 = "http://uta.pw/shodou/img/28/214.png"

    urllib.request.urlretrieve(url1, savename)
    print("urlretrieve ()로 파일이 저장되었습니다")

    ##2. urlopen() 함수사용 저장
    mem = urllib.request.urlopen(url1).read()
    with open(savename, mode="wb") as f:
        f.write(mem)
    print("urlopen()로 파일이 저장되었습니다")

    ##  저장하지 않고 오픈한상태에서 문자열로 처리후 보기
    url2 = "http://api.aoikujira.com/ip/ini"
    mem1 = urllib.request.urlopen(url2).read()

    text1 = mem1.decode("utf-8")  ## 바이너리를 text(문자열)로 변환하기 :  decode('utf-8')
    print('텍스트:'+text1)


    ## url로 요청 접근시 매개변수를 추가하여 접근 : urllib.parse 모듈의 urlencode()함수
    url3 = "http://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp"
    value = {
        'stnId': '108'
    }
    params = urllib.parse.urlencode(value)    ## 매개변수 값을 dict자료형에서 url 코드로 만듬: urlencode() {a: b} = > a = b
    url3 = url3 + "?" + params               ## 요청 전용 URL을 생성합니다 : get방식으로 매개변수 처리
    print("url?param= :", url3)

    mem3 = urllib.request.urlopen(url3).read()
    text2 = mem3.decode("utf-8")            ##  binary 데이터(대부분의 웹 데이터)를 text 문자열로 전환하기: decode()
    # print('매개변수추가하여 웹 접근:'+text2)


    ##3. requests() 패키지 이용(고급)  : HTTP 요청을 보내는 모듈 사용
    req = requests.get("http://wikibook.co.kr/wikibook.png")
    req1 = requests.post("http://api.aoikujira.com/time/get.php")

    text3= req1.text            # 텍스트 형식으로 추출
    print('requests방식으로 텍스트 데이터 :' +text3)

    mem4 = req1.content                      ##   mem = urllib.request.urlopen(url).read()  바이너리 데이터
    text4 = mem4.decode("utf-8")
    # print('requests방식으로 바이너리 데이터 :' +mem4)
    print('requests방식으로 text 데이터 :' +text4)

    with open(savename, "wb") as f:         ##   바이너리 형식으로 png 데이터 저장(text 이외에는 바이너리 형태로 저장)
        f.write(req1.content)
        print("requests()이용한 saved")

    return render(request, 'mLearn/exHome.html')


def beautifulSoup(request):

    # lessen #1 : links
    html = """
    <html><body>
      <ul>
        <li><a href="http://www.naver.com">naver</a></li>
        <li><a href="http://www.daum.net">daum</a></li>
      </ul>
    </body></html>
    """

    soup = BeautifulSoup(html, 'html.parser')
    links = soup.find_all("a")

    # 링크 목록 출력하기 ---
    for a in links:
        href = a.attrs['href']
        text = a.string
        print(text, ">", href)

    # lessen #2 : Tag명으로 분류 : 분석하고 싶은 HTML --- (※2)
    html = """
        <html><body>
          <h1>스크레이핑이란?</h1>
          <p>웹 페이지를 분석하는 것</p>
          <p>원하는 부분을 추출하는 것</p>
        </body></html>
    """
    soup = BeautifulSoup(html, 'html.parser')

    h1 = soup.html.body.h1                          # 원하는 부분 추출하기 -- tag 명으로 추출
    p1 = soup.html.body.p
    p2 = p1.next_sibling.next_sibling

    print("h1 = " + h1.string)                      # 요소의 글자 출력하기 --- (※5)
    print("p  = " + p1.string)
    print("p  = " + p2.string)

    # lessen #3 : 선택자 한개 : soup.select_one(<selector>)  /// 선택자로 여러개 리스트 추출 : soup.select(<selector>)
    html = """
        <html><body>
        <div id="meigen">
          <h1>위키북스 도서</h1>
          <ul class="items">
            <li>유니티 게임 이펙트 입문</li>
            <li>스위프트로 시작하는 아이폰 앱 개발 교과서</li>
            <li>모던 웹사이트 디자인의 정석</li>
          </ul>
        </div>
        </body></html>
    """

    soup = BeautifulSoup(html, 'html.parser')
    h1 = soup.select_one("div#meigen > h1").string          # 타이틀 부분 추출하기 --- (※3)
    print("h1 =", h1)
    li_list = soup.select("div#meigen > ul.items > li")     # 목록 부분 추출하기 --- (※4)
    for li in li_list:
        print("li =", li.string)

    # lessen #4 : 환율 데이터 추출
    req = requests.post("https://finance.naver.com/marketindex/")
    mem4 = req.content

    soup1 = BeautifulSoup(mem4, "html.parser")
    price2 = soup1.select_one("div.head_info > span.value").string
    print('requests usd/krw:', price2)


    url = "https://finance.naver.com/marketindex/"
    res = urllib.request.urlopen(url)
    soup = BeautifulSoup(res, "html.parser")
    price = soup.select_one("div.head_info > span.value").string
    print("urllib.request usd/krw =", price)



    # naver의 주식 사이트 검색
    resp = requests.get('https://finance.naver.com/item/coinfo.nhn?code=005930')
    resp.raise_for_status()

    html = resp.text
    soup = BeautifulSoup(html, 'html.parser')

    items = soup.select("#aside ul li a")

    for item in items:
        print(item.string)

    # investing.com의IBM 주식 사이트에서 내용 발췌
    browser = webdriver.Chrome("C:/Users/ilee/PycharmProjects/mLearn/chromedriver/chromedriver.exe")
    browser.implicitly_wait(3)

    url = "https://www.investing.com/equities/ibm-historical-data"

    ## 로그인페이지 접근
    browser.get(url)

    items = browser.find_elements_by_css_selector("#curr_table tbody tr td")

    for item in items:
        print(item.text)

    browser.quit()



    return render(request, 'mLearn/exHome.html')


## CSS 선택자
def select(request):

    # ## lessen #1 : 기본 선택자
    # # fileName = "C:/Users/ilee/PycharmProjects/mLearn/test.html"
    # # html = open(fileName, encoding="utf-8")
    # html = '''
    #     <html>
    #       <body>
    #         <ul id="bible">
    #           <li id="ge">Genesis</li>
    #           <li id="ex">Exodus</li>
    #           <li id="le">Leviticus</li>
    #           <li id="nu">Numbers</li>
    #           <li id="de">Deuteronomy</li>
    #         </ul>
    #           <ul id = "fr-list">
    #             <li class ="red green" data-lo="ko" > 사과 < / li >
    #             < li class ="purple" data-lo="us" > 포도 </ li >
    #             < li class ="yellow" data-lo="us" > 레몬 < / li >
    #             < li class ="yellow" data-lo="ko" > 오렌지 < / li >
    #           < / ul >
    #           < ul id = "ve-list" >
    #             < li class ="white green" data-lo="ko" > 무 < / li >
    #             < li class ="red green" data-lo="us" > 파프리카 < / li >
    #             < li class ="black" data-lo="ko" > 가지 < / li >
    #             < li class ="black" data-lo="us" > 아보카도 < / li >
    #             < li class ="white" data-lo="cn" > 연근 < / li >
    #           < / ul >
    #       </body>
    #     </html>
    #     '''
    #
    # soup = BeautifulSoup(html, "html.parser")
    #
    # # 다양한 선택자 검색
    # sel = lambda q: print(soup.select_one(q).string)
    #
    # sel("#nu")  # id = nu
    # sel("li#nu")  # li가 id=nu인 태그
    # sel("ul > li#nu")  # ul 밑에 li(id=nu)인 태그
    # sel("#bible #nu")  # id=bible 밑에 id=nu인 태그
    # sel("ul#bible > li#nu")  # ul(id=bible) 밑에 li(id=nu)인 태그
    # sel("li[id='nu']")  # li(id=nu)인 태그
    # sel("li:nth-of-type(4)")  # li 4번째 순서  nth-of-types(1,2,3,4,...)
    #
    # print(soup.select("li")[3].string)  # select의 list에 배열[0,1,2,3,4...]

mLearn/templates/mLearn/exHome.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<style type="text/css">

#body_index{
	background-image:url("{% static 'images/main/city_night.jpg' %}");
}

img {
  display: block;
  max-width:230px;
  max-height:95px;
  width: auto;
  height: auto;
}

/* @media screen and (max-width:768px){
  .card-body{max-height:2em; padding:0;align:center;}
  .card-title{margin:0;align:center;font-size: 0.3em; }
} */
</style>

<div id="body_index" class="p-5">

    <!-- main content -->
    <div class="row col-md-10 offset-md-1 d-flex justify-content-around">

        <div class="col-4 mb-4">
            <div class="card" id="more" >
				<a href="{% url 'mLearn:download' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_1.jpg'%}" alt="Card image" style="width:100%"></a>
				<div class="card-body p-1 d-flex justify-content-center">
					<a href="{% url 'mLearn:download' %}"><h5 class="card-title" style="font-size:3vw">Download</h5></a>
				</div>
            </div>
        </div>
        <div class="col-4 mb-4">
            <div class="card" id="more" >
				<a href="{% url 'mLearn:beautifulSoup' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_1.jpg'%}" alt="Card image" style="width:100%"></a>
				<div class="card-body p-1 d-flex justify-content-center">
					<a href="{% url 'mLearn:beautifulSoup' %}"><h5 class="card-title" style="font-size:3vw">BeautifulSoup</h5></a>
				</div>
            </div>
        </div>
		<div class="col-4 mb-4">
            <div class="card" id="more" >
				<a href="{% url 'mLearn:pandas' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_1.jpg'%}" alt="Card image" style="width:100%"></a>
				<div class="card-body p-1 d-flex justify-content-center">
					<a href="{% url 'mLearn:pandas' %}"><h5 class="card-title" style="font-size:3vw">Pandas</h5></a>
				</div>
            </div>
        </div>
		<div class="col-4 mb-4">
			<div class="card" id="more"  >
	    		<a href="{% url 'mLearn:select' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_3.jpg'%}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
                    <!--<%=cp%>/game/blackjack/start.do-->
	      			<a href="{% url 'mLearn:select' %}"><h5 class="card-title" style="font-size:3vw">Select</h5></a>
	    		</div>
	  		</div>
		</div>
        <div class="col-4 mb-4">
            <div class="card" id="more"  >
                <a href="{% url 'mLearn:path' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_2.jpg'%}" alt="Card image" style="width:100%"></a>
                <div class="card-body p-1 d-flex justify-content-center">
                    <a href="{% url 'mLearn:path' %}"> <h5 class="card-title" style="font-size:3vw">Path</h5></a>
                </div>
            </div>
		</div>
		<div class="col-4 mb-4">
			<div class="card" id="more" >
                <!--<%=cp%>/tutorial/tutorialRequest.do-->
	    		<a href="{% url 'mLearn:login' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_4.jpg'%}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'mLearn:login' %}"><h5 class="card-title" style="font-size:3vw">Login</h5></a>
	    		</div>
	  		</div>
		</div>
		<div class="col-4 mb-4">
			<div class="card" id="more"  >
                <!--<%=cp%>/hshop/hshopMain.do-->
	    		<a href="{% url 'mLearn:weather' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_5.jpg' %}" alt="Card image" style="width:100%">
	    		</a>
	    		<div class="card-body p-1 d-flex justify-content-center">
                    <!--<%=cp%>/hshop/AdminItemForm.do-->
	      			<a href="{% url 'mLearn:weather' %}"><h5 class="card-title" style="font-size:3vw">API </h5></a>
	    		</div>
	  		</div>
		</div>
		<div class="col-4 mb-4">
			<div class="card" id="more"  >
	    		<a href="{% url 'mLearn:selenium' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_11.jpg'%}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
                    <!--<%=cp%>/board/boardWrite.do {}-->
	      			<a href="{% url 'mLearn:selenium' %}"><h5 class="card-title" style="font-size:3vw">Selenium</h5></a>
	    		</div>
	  		</div>
		</div>
		<div class="col-4 mb-4">
			<div class="card" id="more"  >
	    		<a href="{% url 'mLearn:mysql' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_6.jpg' %}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'mLearn:mysql' %}"><h5 class="card-title" style="font-size:3vw">Mysql</h5></a>
	    		</div>
	  		</div>
		</div>
		<div class="col-4 mb-4">
			<div class="card" id="more"  >
	    		<a href="{% url 'mLearn:datatype' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_8.jpg'%}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'mLearn:datatype' %}"><h5 class="card-title" style="font-size:3vw">DataType</h5></a>
	    		</div>
	  		</div>
		</div>
		<div class="col-4 mb-4">
			<div class="card" id="more"  >
	    		<a href="{% url 'mLearn:plot' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_8.jpg'%}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'mLearn:plot' %}"><h5 class="card-title" style="font-size:3vw">Plot</h5></a>
	    		</div>
	  		</div>
		</div>
		<div class="col-4 mb-4">
			<div class="card" id="more"  >
	    		<a href="{% url 'mLearn:image' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_8.jpg'%}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'mLearn:image' %}"><h5 class="card-title" style="font-size:3vw">Image</h5></a>
	    		</div>
	  		</div>
		</div>
		<div class="col-4 mb-4">
			<div class="card" id="more" >
	    		<a href="{% url 'mLearn:scikit' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_9.jpg' %}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'mLearn:scikit' %}"><h5 class="card-title" style="font-size:3vw">Scikit_Learn</h5></a>
	    		</div>
	  		</div>
		</div>
		<div class="col-4 mb-4">
			<div class="card" id="more" >
	    		<a href="{% url 'mLearn:conversion' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_9.jpg' %}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'mLearn:conversion' %}"><h5 class="card-title" style="font-size:3vw">Conversion</h5></a>
	    		</div>
	  		</div>
		</div>
		<div class="col-4 mb-4">
			<div class="card" id="more" >
	    		<a href="{% url 'mLearn:mnist' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_9.jpg' %}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'mLearn:mnist' %}"><h5 class="card-title" style="font-size:3vw">문자인식</h5></a>
	    		</div>
	  		</div>
		</div>
		<div class="col-4 mb-4">
			<div class="card" id="more" >
	    		<a href="{% url 'mLearn:lang' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_9.jpg' %}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'mLearn:lang' %}"><h5 class="card-title" style="font-size:3vw">Language분석</h5></a>
	    		</div>
	  		</div>
		</div>
		<div class="col-4 mb-4">
			<div class="card" id="more" >
	    		<a href="{% url 'mLearn:langTest' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_9.jpg' %}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'mLearn:langTest' %}"><h5 class="card-title" style="font-size:3vw">Language평가</h5></a>
	    		</div>
	  		</div>
		</div>
		<div class="col-4 mb-4">
			<div class="card" id="more" >
	    		<a href="{% url 'mLearn:fat' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_9.jpg' %}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'mLearn:fat' %}"><h5 class="card-title" style="font-size:3vw">비만 평가</h5></a>
	    		</div>
	  		</div>
		</div>
		<div class="col-4 mb-4">
			<div class="card" id="more" >
	    		<a href="{% url 'mLearn:mushroom' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_9.jpg' %}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'mLearn:mushroom' %}"><h5 class="card-title" style="font-size:3vw">랜덤포레스트</h5></a>
	    		</div>
	  		</div>
		</div>
		<div class="col-4 mb-4">
			<div class="card" id="more" >
	    		<a href="{% url 'mLearn:tensor' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_9.jpg' %}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'mLearn:tensor' %}"><h5 class="card-title" style="font-size:3vw">TensorFlow</h5></a>
	    		</div>
	  		</div>
		</div>




		<div class="text-center">
			<input type="button" id="loadMore" class="btn btn-success" value="더보기" />
			<input type="button" class="btn btn-success" value="돌아가기" onclick="history.back(); return false ;" />
		</div>
	</div>

  	<p class="totop"><a href="#top">Back to top</a></p>

</div>
{% endblock %}

mLearn/templates/mLearn/mLearnEdit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block sidebar %}
<div class="col-sm-3">
    {% include 'mLearn/sidebar.html' with objects=mLearnList %}
</div>
{% endblock %}

{% block content %}
<div class="col-sm-9">
    {{form.media }}
    {{item.content|safe }}

    <p class="totop"><a href="#top">Back to top</a></p>
</div>
{% endblock %}